version: '3.4'

services:
  ids-1:
    container_name: ids-1
    image: ${DOCKER_REGISTRY-}identityserverwithspalogin
    build:
      context: .
      dockerfile: IdentityServerWithSpaLogin/Dockerfile
    depends_on:
      - mysql
      - nginx
      - redis
    networks:
      - mynet

  ids-2:
    container_name: ids-2
    image: ${DOCKER_REGISTRY-}identityserverwithspalogin
    build:
      context: .
      dockerfile: IdentityServerWithSpaLogin/Dockerfile
    depends_on:
      - mysql
      - nginx
      - redis
    networks:
      - mynet


  jsclientweb:
    container_name: jsclientweb
    image: ${DOCKER_REGISTRY-}jsclientweb
    build:
      context: .
      dockerfile: JsClientWeb/Dockerfile
    networks:
      - mynet


  productservice:
    container_name: productservice
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    networks:
      - mynet


  orderservice:
    container_name: orderservice
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    networks:
      - mynet


  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
      - mynet


  nginx:
    container_name: nginx
    image: nginx
    restart: always
    networks:
      - mynet


  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - mynet


networks:
  mynet:
    driver: bridge

