version: '3.4'

services:
  ids-1:
    container_name: ids-1
    image: ids
    build:
      context: .
      dockerfile: IdentityServerWithSpaLogin/Dockerfile
    depends_on:
      - mysql
      - nginx-for-ids
      - redis
    networks:
      - mynet

  ids-2:
    container_name: ids-2
    image: ids
    build:
      context: .
      dockerfile: IdentityServerWithSpaLogin/Dockerfile
    depends_on:
      - mysql
      - nginx-for-ids
      - redis
    networks:
      - mynet


  jsclientweb:
    container_name: jsclientweb
    image: ${DOCKER_REGISTRY-}jsclientweb
    build:
      context: .
      dockerfile: JsClientWeb/Dockerfile
    depends_on:
      - nginx-for-client
    networks:
      - mynet


  reactclient:
    container_name: reactclient
    image: ${DOCKER_REGISTRY-}reactclient
    build:
      context: .
      dockerfile: reactclient/Dockerfile
    depends_on:
      - nginx-for-ids
      - nginx-for-api-gateway
    networks:
      - mynet


  productservice:
    container_name: productservice
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    depends_on:
      - nginx-for-api-gateway
    networks:
      - mynet


  orderservice:
    container_name: orderservice
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    depends_on:
      - nginx-for-api-gateway
    networks:
      - mynet


  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
      - mynet


  nginx-for-ids:
    container_name: nginx-for-ids
    image: nginx
    restart: always
    networks:
      - mynet


  nginx-for-client:
    container_name: nginx-for-client
    image: nginx
    restart: always
    depends_on:
      - nginx-for-ids
    networks:
      - mynet



  nginx-for-api-gateway:
    container_name: nginx-for-api-gateway
    image: nginx
    restart: always
    depends_on:
      - nginx-for-ids
    networks:
      - mynet


  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - mynet


networks:
  mynet:
    driver: bridge

