version: '3.4'

services:
  identityserverwithspalogin:
    image: ${DOCKER_REGISTRY-}identityserverwithspalogin
    build:
      context: .
      dockerfile: IdentityServerWithSpaLogin/Dockerfile
    depends_on:
      - docker.mysql
    networks:
      - mynet

  jsclientweb:
    image: ${DOCKER_REGISTRY-}jsclientweb
    build:
      context: .
      dockerfile: JsClientWeb/Dockerfile
    networks:
      - mynet


  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    networks:
      - mynet


  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    networks:
      - mynet


  docker.mysql:
    hostname: docker.mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mynet


networks:
  mynet:
    driver: bridge

