version: '3.4'

services:
  identityserverwithspalogin1:
    image: ${DOCKER_REGISTRY-}identityserverwithspalogin
    build:
      context: .
      dockerfile: IdentityServerWithSpaLogin/Dockerfile
    depends_on:
      - mysql
      - nginx
    networks:
      - mynet

  identityserverwithspalogin2:
    image: ${DOCKER_REGISTRY-}identityserverwithspalogin
    build:
      context: .
      dockerfile: IdentityServerWithSpaLogin/Dockerfile
    depends_on:
      - mysql
      - nginx
    networks:
      - mynet


  jsclientweb:
    image: ${DOCKER_REGISTRY-}jsclientweb
    build:
      context: .
      dockerfile: JsClientWeb/Dockerfile
    networks:
      - mynet


  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    networks:
      - mynet


  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    networks:
      - mynet


  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mynet


  nginx:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynet


networks:
  mynet:
    driver: bridge

